version: "3.8"

services:
  product-microservice-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: product-microservice-api:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - product-network

networks:
  product-network:
    driver: bridge
